observer/urls.py
from django.urls import path
from observer import views

urlpatterns = [
    path('home/', views.index, name='index'),
    path('students/', views.student_list, name="students_list"),
    path('student/new/', views.add_student, name="add_student"),
    path('student/(?P<pk>\d+)/', views.student_detail, name="student_detail"),
    path('^student/(?P<pk>\d+)/edit/$', views.edit_student, name="edit_student"),
    path('sections/', views.section_list, name="sections_list"),
    path('section/new/', views.add_section, name="add_section"),
    path('section/(?P<pk>\d+)/', views.section_detail, name="section_detail"),
    path('^section/(?P<pk>\d+)/edit/$', views.edit_section, name="edit_section"),
    path('ajax/load_sections/', views.load_section, name="ajax_load_sections"),
    path('group/', views.group_list, name="group_list"),
    path('group/new/', views.add_group, name="add_group"),
    path('group/(?P<pk>\d+)/', views.group_detail, name="group_detail"),
    path('^group/(?P<pk>\d+)/edit/$', views.edit_group, name="edit_group"),
    path('ajax/load_groups/', views.load_group, name="ajax_load_groups"),
    path('filial/', views.filial_list, name="filial_list"),
    path('filial/new/', views.add_filial, name="add_filial"),
    path('filial/(?P<pk>\d+)/', views.filial_detail, name="filial_detail"),
    path('^filial/(?P<pk>\d+)/edit/$', views.edit_filial, name="edit_filial"),
    # path('^student/(?P<pk>\d+)/delete/$', views.delete_student, name="delete_student"),
]

visitreg/urls.py
from django.urls import path, include

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    path('index/', include('observer.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

observer/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date


# модель Филиала для Организации
class Filial(models.Model):
    name = models.CharField(max_length=20, help_text="Enter a filial name")
    phone = models.CharField(max_length=20, help_text="Enter Phone of Filial")
    address = models.CharField(max_length=20, help_text="Enter Address of Filial")
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


# модель Направления в школе (бальные танцы, живопись и тп)
class Section(models.Model):
    name = models.CharField(max_length=20, help_text="Enter a section name")
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    filial = models.ForeignKey('Filial', on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


# модель Группы в школе (начинающие, дошкольники и тп)
class Group(models.Model):
    name = models.CharField(max_length=20, help_text="Enter a group name")
    filial = models.ForeignKey('Filial', on_delete=models.SET_NULL, null=True, blank=True)
    section = models.ForeignKey('Section', on_delete = models.SET_NULL, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Ticket(models.Model):
    name = models.CharField(max_length=10, help_text="Enter a ticket name")
    price = models.IntegerField()
    due_date = models.DateField(null=True, blank=True)
    TICKET_TYPE = (
        ('p', 'permanent'),
        ('o', 'one_time'),
    )
    type = models.CharField(max_length=1, choices=TICKET_TYPE, blank=True, default='o', help_text="Choise type of ticket")

    @property
    def is_overdue(self):
        if self.due_date and date.today > self.due_date:
            return True
        return False

    class Meta:
        ordering = ["due_date"]

    def __str__(self):
        return self.name


class Student(models.Model):
    first_name = models.CharField(max_length=20, help_text="Enter First Name of Student")
    last_name = models.CharField(max_length=20, help_text="Enter Last Name of Student")
    phone = models.CharField(max_length=20, help_text="Enter Phone of Student")
    ticket = models.ForeignKey('Ticket', on_delete = models.SET_NULL, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    filial = models.ForeignKey('Filial', on_delete=models.SET_NULL, null=True)
    section = models.ForeignKey('Section', on_delete = models.SET_NULL, null=True)
    group = models.ForeignKey('Group', on_delete = models.SET_NULL, null=True)

    class Meta:
        ordering = ["last_name"]

    def __str__(self):
        return '{0}, {1}'.format(self.first_name, self.last_name)

observer/forms.py
from django import forms
from .models import Student, Section, Group, Filial


class StudentForm(forms.ModelForm):
    class Meta:
        model=Student
        fields = ('first_name', 'last_name', 'phone', 'ticket', 'filial', 'section', 'group')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['section'].queryset = Section.objects.none()
        self.fields['group'].queryset = Group.objects.none()

        if 'filial' in self.data:
            try:
                filial_id = int(self.data.get('filial'))
                self.fields['section'].queryset = Section.objects.filter(filial_id=filial_id).order_by('name')
                section_id = int(self.data.get('section'))
                self.fields['group'].queryset = Group.objects.filter(section_id=section_id).order_by('name')
            except(ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['section'].queruset = self.instance.filial.section_set.order_by('name')
            self.fields['group'].queruset = self.instance.section.group_set.order_by('name')


class SectionForm(forms.ModelForm):
    class Meta:
        model=Section
        fields = ('name','filial')


class GroupForm(forms.ModelForm):
    class Meta:
        model=Group
        fields = ('name', 'filial', 'section')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['section'].queryset = Section.objects.none()

        if 'filial' in self.data:
            try:
                filial_id = int(self.data.get('filial'))
                self.fields['section'].queryset = Section.objects.filter(filial_id=filial_id).order_by('name')
            except(ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['section'].queruset = self.instance.filial.section_set.order_by('name')


class FilialForm(forms.ModelForm):
    class Meta:
        model=Filial
        fields = ('name', 'phone', 'address')

observer/views.py
from django.shortcuts import render, get_object_or_404, redirect
from observer.models import Student, Section, Group, Filial
from .forms import StudentForm, SectionForm, GroupForm, FilialForm
from django.contrib.auth.decorators import login_required


def index(request):
    return render(
        request,
        'observer/index.html',
    )


# методы обработки Филиалов
@login_required()
def filial_list(request):
    # выбираются филиалы, принадлежащие текущему пользователю
    filials = Filial.objects.filter(owner=request.user)
    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits + 1
    return render(
        request,
        'observer/filial_list.html',
        {'filials': filials, 'num_visits': num_visits}
    )


def add_filial(request):
    if request.method == "POST":
        form = FilialForm(request.POST)
        if form.is_valid():
            filial = form.save(commit=False)
            # полю Owner присваивается текущий пользователь
            filial.owner = request.user
            filial = form.save()
            return redirect('filial_detail', pk=filial.pk)
    else:
        form = FilialForm()
    return render(
        request,
        'observer/add_filial.html',
        {'form': form}
    )


def filial_detail(request, pk):
    filial = get_object_or_404(Filial, pk=pk)
    return render(
        request,
        'observer/filial_detail.html',
        {'filial':filial}
    )


def edit_filial(request, pk):
    filial = get_object_or_404(Filial, pk=pk)
    if request.method == "POST":
        form = FilialForm(request.POST, instance=filial)
        if form.is_valid():
            filial = form.save()
            return redirect('filial_detail', pk=filial.pk)
    else:
        form = FilialForm(instance=filial)
    return render(
        request,
        'observer/add_filial.html',
        {'form': form}
    )


# методы обработки Направлений учебы
@login_required()
def section_list(request):
    # выбираются секции (направления занятий), принадлежащие текущему пользователю
    sections = Section.objects.filter(owner=request.user)
    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits + 1
    return render(
        request,
        'observer/section_list.html',
        {'sections': sections, 'num_visits': num_visits}
    )


def add_section(request):
    if request.method == "POST":
        form = SectionForm(request.POST)
        if form.is_valid():
            section = form.save(commit=False)
            # полю Owner присваивается текущий пользователь
            section.owner = request.user
            section = form.save()
            return redirect('section_detail', pk=section.pk)
    else:
        form = SectionForm()
    return render(
        request,
        'observer/add_section.html',
        {'form': form}
    )


def section_detail(request, pk):
    section = get_object_or_404(Section, pk=pk)
    return render(
        request,
        'observer/section_detail.html',
        {'section':section}
    )


def edit_section(request, pk):
    section = get_object_or_404(Section, pk=pk)
    if request.method == "POST":
        form = SectionForm(request.POST, instance=section)
        if form.is_valid():
            section = form.save()
            return redirect('section_detail', pk=section.pk)
    else:
        form = SectionForm(instance=section)
    return render(
        request,
        'observer/add_section.html',
        {'form': form}
    )


# методы обработки Групп обучения
@login_required()
def group_list(request):
    # выбираются группы, принадлежащие текущему пользователю
    groups = Group.objects.filter(owner=request.user)
    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits + 1
    return render(
        request,
        'observer/group_list.html',
        {'groups': groups, 'num_visits': num_visits}
    )


def load_section(request):
    filial_id = request.GET.get('filial')
    sections = Section.objects.filter(filial_id=filial_id).order_by('name')
    return render(request, 'observer/section_dropdown_list_option.html', {'sections':sections})


def add_group(request):
    if request.method == "POST":
        form = GroupForm(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            # полю Owner присваивается текущий пользователь
            group.owner = request.user
            group = form.save()
            return redirect('group_detail', pk=group.pk)
    else:
        form = GroupForm()
    return render(
        request,
        'observer/add_group.html',
        {'form': form}
    )


def group_detail(request, pk):
    group = get_object_or_404(Group, pk=pk)
    return render(
        request,
        'observer/group_detail.html',
        {'group':group}
    )


def edit_group(request, pk):
    group = get_object_or_404(Group, pk=pk)
    if request.method == "POST":
        form = GroupForm(request.POST, instance=group)
        if form.is_valid():
            group = form.save()
            return redirect('group_detail', pk=group.pk)
    else:
        form = GroupForm(instance=group)
    return render(
        request,
        'observer/add_group.html',
        {'form': form}
    )


# методы обработки студентов
@login_required()
def student_list(request):
    # выбираются студенты, принадлежащие текущему пользователю
    students = Student.objects.filter(owner=request.user)
    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits + 1
    return render(
        request,
        'observer/student_list.html',
        {'students': students, 'num_visits': num_visits}
    )


def student_detail(request, pk):
    student = get_object_or_404(Student, pk=pk)
    return render(
        request,
        'observer/student_detail.html',
        {'student':student}
    )


def load_group(request):
    filial_id = request.GET.get('filial')
    sections = Section.objects.filter(filial_id=filial_id).order_by('name')
    section_id = request.GET.get('section')
    groups = Group.objects.filter(section_id=section_id).order_by('name')
    return render(request, 'observer/group_dropdown_list_option.html', {'sections': sections, 'groups': groups})


def add_student(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            student = form.save(commit=False)
            # полю Owner присваивается текущий пользователь
            student.owner = request.user
            student = form.save()
            return redirect('student_detail', pk=student.pk)
    else:
        form = StudentForm()
    return render(
        request,
        'observer/add_student.html',
        {'form': form}
    )


def edit_student(request, pk):
    student = get_object_or_404(Student, pk=pk)
    if request.method == "POST":
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            student = form.save()
            return redirect('student_detail', pk=student.pk)
    else:
        form = StudentForm(instance=student)
    return render(
        request,
        'observer/add_student.html',
        {'form': form}
    )


def delete_student(request, pk):
    student = get_object_or_404(Student,pk=pk)
    student.delete()
    return redirect('student_list')

observer/templates/observer/add_filial.html
{% extends "observer/base_generic.html" %}

{% block title %}
    <title>Add new Filial</title>
{% endblock %}

{% block content %}
    <h1>Add new filial</h1>
    <form method="post">{% csrf_token %}
        {{form.as_p}}
        <button type="submit">Save</button>
    </form>
{% endblock %}

observer/templates/observer/add_group.html
{% extends "observer/base_generic.html" %}

{% block title %}
    <title>Add new Group</title>
{% endblock %}

{% block content %}
    <h1>Add new group</h1>
    <form method="post" id="groupForm" data-sections-url="{% url 'ajax_load_sections' %}" novalidate>
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button type="submit">Save</button>
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
    $("#id_filial").change(function () {
      var url = $("#groupForm").attr("data-sections-url");      // get the url of the `load_sections` view
      var filialId = $(this).val();                            // get the selected filial ID from the HTML input

      $.ajax({                                                // initialize an AJAX request
        url: url,                                             // set the url of the request (= localhost:8000/ajax/load_sections/)
        data: {
          'filial': filialId                                // add the filial id to the GET parameters
        },
        success: function (data) {                            // `data` is the return of the `load_groups` view function
          $("#id_section").html(data);                          // replace the contents of the section input with the data that came from the server
        }
      });

    });
  </script>
{% endblock %}

observer/templates/observer/add_section.html
{% extends "observer/base_generic.html" %}

{% block title %}
    <title>Add new Section</title>
{% endblock %}

{% block content %}
    <h1>Add new section</h1>
    <form method="post">{% csrf_token %}
        {{form.as_p}}
        <button type="submit">Save</button>
    </form>
{% endblock %}

observer/templates/observer/add_student.html
{% extends "observer/base_generic.html" %}

{% block title %}
    <title>Add new Student</title>
{% endblock %}

{% block content %}
    <h1>Add new student</h1>
    <form method="post" id="studentForm" data-sections-url="{% url 'ajax_load_groups' %}" novalidate>
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button type="submit">Save</button>
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
    $("#id_filial").change(function () {
      var url_sections = $("#studentForm").attr("data-sections-url");      // get the url of the `load_groups` view
      var filialId = $(this).val();                            // get the selected filial ID from the HTML input

      $.ajax({                                                // initialize an AJAX request
        url: url_sections,                                             // set the url of the request (= localhost:8000/ajax/load_groups/)
        data: {
          'filial': filialId                                // add the filial id to the GET parameters
        },
        success: function (data) {                            // `data` is the return of the `load_groups` view function
          $("#id_section").html(data);                          // replace the contents of the section input with the data that came from the server
        }
      });

    });
  </script>
  <script>
    $("#id_section").change(function () {
      var url_groups = $("#studentForm").attr("data-sections-url");      // get the url of the `load_groups` view
      var sectionId = $(this).val();

      $.ajax({                                                // initialize an AJAX request
        url: url_groups,                                             // set the url of the request (= localhost:8000/ajax/load_groups/)
        data: {
          'section': sectionId                                // add the filial id to the GET parameters
        },
        success: function (data) {                            // `data` is the return of the `load_groups` view function
          $("#id_group").html(data);                          // replace the contents of the section input with the data that came from the server
        }
      });

    });
  </script>

{% endblock %}

observer/templates/observer/base_generic.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    {% block title %}<title>Title</title>{% endblock %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <!-- Добавление дополнительного статического CSS файла -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                        <li>User: {{user.get_username}}</li>
                        <li><a href="{% url 'students_list' %}">Students</a></li>
                        <li><a href="{% url 'add_student' %}">Add new student</a></li>
                        <li><br></li>
                        <li><a href="{% url 'sections_list' %}">Sections</a></li>
                        <li><a href="{% url 'add_section' %}">Add new section</a></li>
                        <li><br></li>
                        <li><a href="{% url 'group_list' %}">Groups</a></li>
                        <li><a href="{% url 'add_group' %}">Add new group</a></li>
                        <li><br></li>
                        <li><a href="{% url 'filial_list' %}">Filials</a></li>
                        <li><a href="{% url 'add_filial' %}">Add new filial</a></li>
                        <li><br></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10">
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

observer/templates/observer/filial_detail.html
{% extends "observer/base_generic.html" %}

{% block title %}
    <title>Filial detail</title>
{% endblock %}

{% block content %}
    <div>
        <h3>Name of Filial: {{filial.name}}</h3>
        <h3>Phone of Filial: {{filial.phone}}</h3>
        <h3>Address of Filial: {{filial.address}}</h3>
    </div>
{% endblock %}

observer/templates/observer/filial_list.html
{% extends "observer/base_generic.html" %}

{% block title %}
    <title>Filial</title>
{% endblock %}

{% block content %}
<h1 class="page-header">
    Filials
</h1>
<table class="table" id="student-table">
    <thead>
        <tr>
            <th>#</th>
            <th>Filial Name</th>
            <th>Filial Phone</th>
            <th>Filial Address</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for filial in filials %}
        <tr>
            <td>{{filial.id}}</td>
            <td><a href="{% url 'filial_detail' pk=filial.pk %}">{{filial.name}}</a></td>
            <td>{{filial.phone}}</td>
            <td>{{filial.address}}</td>
            <td><a class="btn btn-default" href="{% url 'edit_filial' pk=filial.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="7" class="text-center bg-warning">No filial</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<p>You have visited this page {{num_visits}} times</p>
{% endblock %}

observer/templates/observer/group_dropdown_list_option.html
<option value=""></option>
{% for section in sections %}
    <option value="{{section.pk}}">{{section.name}}</option>
{% endfor %}
{% for group in groups %}
    <option value="{{group.pk}}">{{group.name}}</option>
{% endfor %}

observer/templates/observer/group_list.html
{% extends "observer/base_generic.html" %}

{% block title %}
    <title>Group</title>
{% endblock %}

{% block content %}
<h1 class="page-header">
    Groups
</h1>
<table class="table" id="student-table">
    <thead>
        <tr>
            <th>#</th>
            <th>Group Name</th>
            <th>Section Name</th>
            <th>Filial Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for group in groups %}
        <tr>
            <td>{{group.id}}</td>
            <td><a href="{% url 'group_detail' pk=group.pk %}">{{group.name}}</a></td>
            <td>{{group.section}}</td>
            <td>{{group.filial}}</td>
            <td><a class="btn btn-default" href="{% url 'edit_group' pk=group.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="7" class="text-center bg-warning">No group</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<p>You have visited this page {{num_visits}} times</p>
{% endblock %}

observer/templates/observer/index.html
{% extends "observer/base_generic.html" %}

{% block title %}
    <title>Homepage</title>
{% endblock %}

{% block content %}
<h1>Visit Observer</h1>
    <p>Welcome to <em>Visit Observer</em> site</p>
{% endblock %}

observer/templates/observer/section_dropdown_list_option.html
<option value=""></option>
{% for section in sections %}
    <option value="{{section.pk}}">{{section.name}}</option>
{% endfor %}

observer/templates/observer/section_list.html
{% extends "observer/base_generic.html" %}

{% block title %}
    <title>Sections</title>
{% endblock %}

{% block content %}
<h1 class="page-header">
    Sections
</h1>
<table class="table" id="student-table">
    <thead>
        <tr>
            <th>#</th>
            <th>Section Name</th>
            <th>Filial Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for section in sections %}
        <tr>
            <td>{{section.id}}</td>
            <td><a href="{% url 'section_detail' pk=section.pk %}">{{section.name}}</a></td>
            <td>{{section.filial}}</td>
            <td><a class="btn btn-default" href="{% url 'edit_section' pk=section.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="7" class="text-center bg-warning">No section</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<p>You have visited this page {{num_visits}} times</p>
{% endblock %}

observer/templates/observer/student_detail.html
{% extends "observer/base_generic.html" %}

{% block title %}
    <title>Student detail</title>
{% endblock %}

{% block content %}
    <div>
        <h3>Last Name: {{student.last_name}}</h3>
        <h3>First Name: {{student.first_name}}</h3>
        <h3>Phone: {{student.phone}}</h3>
        <h3>Ticket: {{student.ticket}}</h3>
    </div>
{% endblock %}

observer/templates/observer/student_list.html
{% extends "observer/base_generic.html" %}

{% block title %}
    <title>Students</title>
{% endblock %}

{% block content %}
<h1 class="page-header">
    Students
</h1>
<table class="table" id="student-table">
    <thead>
        <tr>
            <th>#</th>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Phone</th>
            <th>Ticket Type</th>
            <th>Filial</th>
            <th>Section</th>
            <th>Group</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for student in students %}
        <tr>
            <td>{{student.id}}</td>
            <td><a href="{% url 'student_detail' pk=student.pk %}">{{student.last_name}}</a></td>
            <td>{{student.first_name}}</td>
            <td>{{student.phone}}</td>
            <td>{{student.ticket}}</td>
            <td>{{student.filial}}</td>
            <td>{{student.section}}</td>
            <td>{{student.group}}</td>
            <td><a class="btn btn-default" href="{% url 'edit_student' pk=student.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="7" class="text-center bg-warning">No student</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<p>You have visited this page {{num_visits}} times</p>
{% endblock %}